### ISSUE TITLE
Crash on right click interaction

### ISSUE THREAD

**Issue by blockbreaker1361** [KidsDontPlay/Quick-Crafting#4]
When I attempt to right click either the full table or portable version, I get this crash.
http://pastebin.com/VTFDuxyu

**Comment by KidsDontPlay** [comment]
Mmh.. I guess the problem is your forge version.
Does it crash with 10.13.4.1448 too?

**Comment by blockbreaker1361** [comment]
I don't know if it crashes with 1448 cause I'm on 1566. I don't want to go back to that version. Can you update to latest Forge build please?

**Comment by KidsDontPlay** [comment]
Could you try this jar https://drive.google.com/file/d/0Bxk8bebSTRk-emwtckRZQ1A4ZXM/view?usp=sharing
And show me the fml-client-latest.log after opening the crafting table.

**Comment by blockbreaker1361** [comment]
Sorry it took so long. I was out of town. I hope this is what you need.
http://pastebin.com/uu0iHaht

**Comment by KidsDontPlay** [comment]
That's odd. It seems that a mod adds a recipe with an itemstack without item.
May you try this one https://drive.google.com/file/d/0Bxk8bebSTRk-UUxoQjhYejVvUFE/view?usp=sharing
I shouldn't crash but the affected recipe(s) are not craftable in the quick crafting table.

**Comment by blockbreaker1361** [comment]
I got the GUI for the crafting table to come up, but when I clicked on an item, this happened...
http://pastebin.com/pLfmqH8i

**Comment by KidsDontPlay** [comment]
Ok, that' s another crash. I fixed it.
I'm gonna release the file tomorrow

**Comment by blockbreaker1361** [comment]
Cool! I'll test it out then and hope for the best. :)
