### ISSUE TITLE
3 Sugar Cane equals 3 Sugar .. and 1 Iron Bucket?

### ISSUE THREAD

**Issue by Vaygrim** [KidsDontPlay/Quick-Crafting#5]
Version 1.3 off Curse, I get the above oddity. Seems to only happen with sugar cane, not sure why. If you need a list of other mods I'm using in the pack, or a test copy of the pack .. let me know!

**Comment by KidsDontPlay** [comment]
I don't really understand. Do you mean that the iron bucket is shown in the table if you have 3 sugar canes in your inventory?

**Comment by Vaygrim** [comment]
Let's say I have a stack of 64 Sugar Cane in my inventory. I left click "3 Paper" once in the QuickCrafting Table, and I get 3 Paper on my pointer. BUT.. I also have 1 Iron Bucket just magically 'appear' in my inventory.

**Comment by Vaygrim** [comment]
Just for the record I also would like to say that I really LOVE this mod and I am extremely happy that someone is maintaining a mod of this type. I have a casual-centric modpack that I am putting together and a crafting table like this is super useful for casual players.

**Comment by KidsDontPlay** [comment]
Ok, I got it.
I guess the problem is the recipe for paper from thermal expansion/foundation because it needs a water bucket. I'll see what I can do

**Comment by Vaygrim** [comment]
Oooh, I didn't even KNOW about that version of the recipe. Wait, doesn't that one use wood pulp / sawdust tho? Not sugar cane?

**Comment by KidsDontPlay** [comment]
You're right. It's a bug
